### ISSUE TITLE
CreateHandle() Error when running fprint on raspberry Pi 2 with Digital Persona u4500

### ISSUE THREAD

**Issue by mctrp** [ephraim/node-fprint#1]
Hi Ephraim,

First of all, thank you for porting the fprint library to nodejs and node-red!

As part of my never ending quest to automate my home I am trying to set up a Digital Persona u.are.u 4500 fingerprint reader on a Raspberry Pi 2 running Raspbian Jessie. However I've run into a problem and I don't know how to solve it. Whenever I try to the code and try to enroll/verify a fingerprint I receive the following error:

`pi@raspberrypi:~/node_modules/node-fprint/test $ node verify.js
Found: Digital Persona U.are.U 4000/4000B/4500
enroll your finger! You will need swipe your finger 1 times.
stage 1/1
uru4000:info [init_run_state] Versions 0010 and 0115
`

----presents finger on reader----

`FATAL ERROR: v8::HandleScope::CreateHandle() Cannot create a handle without a HandleScope
Aborted
`

Do you have any idea what is causing this exception and/or how to solve it?

Kind regards,

Marcel

node-fprint: 0.0.6
node-red-contrib-fprint: 0.0.4
Nodejs: 4.4.3-1
Raspbian Jessie Lite,  March 2016
Kernel version: 4.4

**Comment by ephraim** [comment]
Hey,
thanks for your detailed feedback. node-fprint is build against nodejs 0.12 and I've never tested it against any newer versions of nodejs. 
So, this is most probably a problem with compatibility to your nodejs version.

I'll try to fix it in the next days but cannot promise anything.

**Comment by mctrp** [comment]
Hi,

Thanks for our quick response!

After some digging around I found the following thread:
[https://github.com/nodejs/nan/issues/440](url)

There they were encountering a similar problem, which they solved by replacing
`Nan::HandleScope();`
with
`Nan::HandleScope scope;`.

I've rebuild from the supplied source code with this change and this solved the error message apparently. It also fixes the node-red implementation of fprint!

```
pi@raspberrypi:~/node_modules/node-fprint/test $ node verify.js
Found: Digital Persona U.are.U 4000/4000B/4500
enroll your finger! You will need swipe your finger 1 times.
stage 1/1
uru4000:info [init_run_state] Versions 0010 and 0115
enroll-completed

fingerprint size: 870
now your finger will be verified. Please swipe your finger once again.
uru4000:info [init_run_state] Versions 0010 and 0115
verfiy-succeeded
MATCHED.
libusb: error [handle_events] hotplug pipe read error -1 != 8
node: pthread_mutex_lock.c:151: __pthread_mutex_lock: Assertion '((mutex)->__data.__kind & 127) == PTHREAD_MUTEX_ERRORCHECK_NP' failed.
Aborted
```

(the error messages at the end seem to originate from libusb, don't know if they are important)

I've made a pull request with the suggested changes.

Cheers,

Marcel

**Comment by ephraim** [comment]
pull request accepted. version 0.0.7 released with this change.
