### ISSUE TITLE
Fingerprints overflow

### ISSUE THREAD

**Issue by sebastiaoLa** [ephraim/node-fprint#12]
When I spend 54 or more fingerprints for identifyStart function, it does not turn on my reader, maybe an overflow of fingerprints? kk

**Comment by ephraim** [comment]
I had a quick glance at the code, but couldn't identify any possible reason for such a behave.
It dynamically allocates as much fp data as it needs.
I'm very curious what the problem is.
Perhaps adding some debug output in the identify.cpp can help to sort this out.

**Comment by sebastiaoLa** [comment]
futher tests reduced the number to 13
how do i add this debug output?

**Comment by sebastiaoLa** [comment]
futher tests reduced the number to 13
how do i add this debug output?

**Comment by sebastiaoLa** [comment]
I'm sorry i took so long to respond in here, it was my fault, i was sending the wrong array, further reading of the code revealed that to me. thanks for the help
