### ISSUE TITLE
failed on npm i in window 10

### ISSUE THREAD

**Issue by singhsandip** [ephraim/node-fprint#13]
I have tried to use this library on windows 10 but when i run the installation command i end up at getting following error:-

 Call to 'pkg-config --libs libfprint' returned exit status -1073741701 while in binding.gyp. while trying to load binding.gyp

**Comment by c0nstructer** [comment]
Same issue on OSX, any idas?

**Comment by ephraim** [comment]
This nodejs node is a wrapper around the libfprint library.
So libfprint is mandatory for this node to be available on any os which it should be used.
You will need to get libfprint binary for your OS or compile libfprint yourself. Then replace the pkg-config part so node-fprint can find libfprint. But this is no issue of node-fprint. Have a look at libfprint to get help about this problem.

**Comment by c0nstructer** [comment]
node-fprint is also obsolete, and doesn’t install. I quest I’ll compline
libfprint, or write a small functions what I need for myself.
