### ISSUE TITLE
failed to install

### ISSUE THREAD

**Issue by leongsiong** [ephraim/node-fprint#4]
excute this command,
npm install node-fprint

below are the error log

> node-fprint@0.0.7 install /root/node_modules/node-fprint
> node-gyp rebuild

Package libfprint was not found in the pkg-config search path.
Perhaps you should add the directory containing `libfprint.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libfprint' found
gyp: Call to 'pkg-config --libs libfprint' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error:`gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Linux 4.6.3-1-ARCH
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/node_modules/node-fprint
gyp ERR! node -v v6.3.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open '/root/package.json'
npm WARN root No description
npm WARN root No repository field.
npm WARN root No README data
npm WARN root No license field.
npm ERR! Linux 4.6.3-1-ARCH
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "--save" "install" "node-fprint"
npm ERR! node v6.3.0
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE

npm ERR! node-fprint@0.0.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-fprint@0.0.7 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-fprint package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-fprint
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-fprint
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/npm-debug.log

**Comment by ephraim** [comment]
> No package 'libfprint' found

Most probably you should install libfprint-dev package.

**Comment by leongsiong** [comment]
Hi,
Please advise where and how tom install 'libfprint' package.

Thanks

**Comment by leongsiong** [comment]
Thanks.
working ok now.
using 'pacman -S libfprint' command

**Comment by singhsandip** [comment]
how can we install libfprint-dev package on windows 10
