### ISSUE TITLE
Identify fingerprint as parameter.

### ISSUE THREAD

**Issue by Ellebkey** [ephraim/node-fprint#7]
First of all I've like to congrats you for this node wrap. 

I'm working on a platform with a principal machine (server) and have some raspberries(clients) conected with my fingerprint lectors (Digital Persona U.are.U) where I'm expecting to have at least 500 different users. With the enrollStart() I'm saving the fingerprint String on a database, and when I need to Identify someone I create an Array as you have on the example. I see that the identifyStart() needs this array and when you put the finger in compares, but Is there a way with this library where I can read only the fingerprint on my client, and send it to the server and compare it there?

Thanks for your help and happy holidays!

**Comment by ephraim** [comment]
You want a identify on the server without a fingerprintsensor connected? I would name this identifymatch where you have both the enrolled fingerprints and the captured fingerprint which should be compared.

As far as I remember, this isn't possible with the libfprint, which is used in the backend. 

Please correct me if I'm wrong or if I missunderstood you.

**Comment by Ellebkey** [comment]
I will have connected the fingerprintsensor, Iwant to read the fingerprint and then send it to the server and do the indentify there. As far as I be researching I know that the identify is live, but I wanted to ask.

**Comment by ephraim** [comment]
There is no serverside matching AFAIK.
closing it.
