### ISSUE TITLE
Could not locate the bindings file.

### ISSUE THREAD

**Issue by ezequiel454** [ephraim/node-fprint#8]
Hi, do you guys know whats the problem ?

  throw err
  ^

Error: Could not locate the bindings file. Tried:
 → C:\Users\Conceito 05\Desktop\node-fprint\build\fingerprint.node
 → C:\Users\Conceito 05\Desktop\node-fprint\build\Debug\fingerprint.node
 → C:\Users\Conceito 05\Desktop\node-fprint\build\Release\fingerprint.node
 → C:\Users\Conceito 05\Desktop\node-fprint\out\Debug\fingerprint.node
 → C:\Users\Conceito 05\Desktop\node-fprint\Debug\fingerprint.node
 → C:\Users\Conceito 05\Desktop\node-fprint\out\Release\fingerprint.node
 → C:\Users\Conceito 05\Desktop\node-fprint\Release\fingerprint.node
 → C:\Users\Conceito 05\Desktop\node-fprint\build\default\fingerprint.node
 → C:\Users\Conceito 05\Desktop\node-fprint\compiled\8.4.0\win32\x64\fingerprint.node
    at bindings (C:\Users\Conceito 05\Desktop\node-fprint\node_modules\bindings\bindings.js:93:9)
    at Object.<anonymous> (C:\Users\Conceito 05\Desktop\node-fprint\index.js:1:95)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Function.Module.runMain (module.js:609:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:598:3

**Comment by ephraim** [comment]
Hey!

The node-fprint is not found in the NODE_PATH of bootstrap. Just place the node-fprint in one of the searched folder as expected by bootstrap.

Cheers,
Ephraim
PS: Where you able to compile node-fprint on windows!? ....

**Comment by ezequiel454** [comment]
Hi Ephraim, thanks for the fast answer, i am using windows, is it a problem?  I never use node_path to config ao i am kind lost haha.

**Comment by twferrell** [comment]
I believe your entire assumption of the use of this module is incorrect.   This node module wraps libfprint library which is a Linux based library.   If you are running this on Windows,  pretty sure that's not going to work out.

**Comment by ezequiel454** [comment]
Oh.. ok twferrel i will install a vw to use test linux. Thank you.

**Comment by ephraim** [comment]
seems to be done .... closing it.
